//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package errors ;import (_ed "fmt";_a "golang.org/x/xerrors";);func (_ag *processError )Unwrap ()error {return _ag ._c };func _ga (_ac ,_ea string )*processError {return &processError {_gd :"\u005b\u0055\u006e\u0069\u0050\u0044\u0046\u005d",_ee :_ac ,_ab :_ea };
};var _ _a .Wrapper =(*processError )(nil );func Error (processName ,message string )error {return _ga (message ,processName )};func Errorf (processName ,message string ,arguments ...interface{})error {return _ga (_ed .Sprintf (message ,arguments ...),processName );
};func Wrap (err error ,processName ,message string )error {if _gf ,_cg :=err .(*processError );_cg {_gf ._gd ="";};_aa :=_ga (message ,processName );_aa ._c =err ;return _aa ;};func Wrapf (err error ,processName ,message string ,arguments ...interface{})error {if _b ,_ff :=err .(*processError );
_ff {_b ._gd ="";};_acg :=_ga (_ed .Sprintf (message ,arguments ...),processName );_acg ._c =err ;return _acg ;};type processError struct{_gd string ;_ab string ;_ee string ;_c error ;};func (_f *processError )Error ()string {var _d string ;if _f ._gd !=""{_d =_f ._gd ;
};_d +="\u0050r\u006f\u0063\u0065\u0073\u0073\u003a "+_f ._ab ;if _f ._ee !=""{_d +="\u0020\u004d\u0065\u0073\u0073\u0061\u0067\u0065\u003a\u0020"+_f ._ee ;};if _f ._c !=nil {_d +="\u002e\u0020"+_f ._c .Error ();};return _d ;};