//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package endian ;import (_f "encoding/binary";_fe "unsafe";);func IsBig ()bool {return _a };func init (){const _ce =int (_fe .Sizeof (0));_g :=1;_ab :=(*[_ce ]byte )(_fe .Pointer (&_g ));if _ab [0]==0{_a =true ;ByteOrder =_f .BigEndian ;}else {ByteOrder =_f .LittleEndian ;
};};var (ByteOrder _f .ByteOrder ;_a bool ;);func IsLittle ()bool {return !_a };