//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package endian ;import (_ed "encoding/binary";_c "unsafe";);func IsBig ()bool {return _edd };func init (){const _b =int (_c .Sizeof (0));_d :=1;_f :=(*[_b ]byte )(_c .Pointer (&_d ));if _f [0]==0{_edd =true ;ByteOrder =_ed .BigEndian ;}else {ByteOrder =_ed .LittleEndian ;
};};var (ByteOrder _ed .ByteOrder ;_edd bool ;);func IsLittle ()bool {return !_edd };