/*
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.md', which is part of this source code package.
 */
/*
 * The embedded character metrics specified in this file are distributed under the terms listed in
 * ./afms/MustRead.html.
 */

package fonts

const (
	// CourierName is a PDF name of the Courier font.
	CourierName = "Courier"
	// CourierBoldName is a PDF name of the Courier (bold) font.
	CourierBoldName = "Courier-Bold"
	// CourierObliqueName is a PDF name of the Courier (oblique) font.
	CourierObliqueName = "Courier-Oblique"
	// CourierBoldObliqueName is a PDF name of the Courier (bold, oblique) font.
	CourierBoldObliqueName = "Courier-BoldOblique"
)

// NewFontCourier returns a new instance of the font with a default encoder set (WinAnsiEncoding).
func NewFontCourier() Type1Font {
	return NewType1Font(CourierName, CourierCharMetrics)
}

// NewFontCourierBold returns a new instance of the font with a default encoder set (WinAnsiEncoding).
func NewFontCourierBold() Type1Font {
	return NewType1Font(CourierBoldName, CourierBoldCharMetrics)
}

// NewFontCourierOblique returns a new instance of the font with a default encoder set (WinAnsiEncoding).
func NewFontCourierOblique() Type1Font {
	return NewType1Font(CourierObliqueName, CourierObliqueCharMetrics)
}

// NewFontCourierBoldOblique returns a new instance of the font with a default encoder set
// (WinAnsiEncoding).
func NewFontCourierBoldOblique() Type1Font {
	return NewType1Font(CourierBoldObliqueName, CourierBoldObliqueCharMetrics)
}

const (
	courierWx = 600.000000
)

// CourierCharMetrics are the font metrics loaded from afms/Courier.afm.  See afms/MustRead.html for
// license information.
//
// TODO(dennwc): unexport
var CourierCharMetrics = map[GlyphName]CharMetrics{
	"A":              {GlyphName: "A", Wx: courierWx},
	"AE":             {GlyphName: "AE", Wx: courierWx},
	"Aacute":         {GlyphName: "Aacute", Wx: courierWx},
	"Abreve":         {GlyphName: "Abreve", Wx: courierWx},
	"Acircumflex":    {GlyphName: "Acircumflex", Wx: courierWx},
	"Adieresis":      {GlyphName: "Adieresis", Wx: courierWx},
	"Agrave":         {GlyphName: "Agrave", Wx: courierWx},
	"Amacron":        {GlyphName: "Amacron", Wx: courierWx},
	"Aogonek":        {GlyphName: "Aogonek", Wx: courierWx},
	"Aring":          {GlyphName: "Aring", Wx: courierWx},
	"Atilde":         {GlyphName: "Atilde", Wx: courierWx},
	"B":              {GlyphName: "B", Wx: courierWx},
	"C":              {GlyphName: "C", Wx: courierWx},
	"Cacute":         {GlyphName: "Cacute", Wx: courierWx},
	"Ccaron":         {GlyphName: "Ccaron", Wx: courierWx},
	"Ccedilla":       {GlyphName: "Ccedilla", Wx: courierWx},
	"D":              {GlyphName: "D", Wx: courierWx},
	"Dcaron":         {GlyphName: "Dcaron", Wx: courierWx},
	"Dcroat":         {GlyphName: "Dcroat", Wx: courierWx},
	"Delta":          {GlyphName: "Delta", Wx: courierWx},
	"E":              {GlyphName: "E", Wx: courierWx},
	"Eacute":         {GlyphName: "Eacute", Wx: courierWx},
	"Ecaron":         {GlyphName: "Ecaron", Wx: courierWx},
	"Ecircumflex":    {GlyphName: "Ecircumflex", Wx: courierWx},
	"Edieresis":      {GlyphName: "Edieresis", Wx: courierWx},
	"Edotaccent":     {GlyphName: "Edotaccent", Wx: courierWx},
	"Egrave":         {GlyphName: "Egrave", Wx: courierWx},
	"Emacron":        {GlyphName: "Emacron", Wx: courierWx},
	"Eogonek":        {GlyphName: "Eogonek", Wx: courierWx},
	"Eth":            {GlyphName: "Eth", Wx: courierWx},
	"Euro":           {GlyphName: "Euro", Wx: courierWx},
	"F":              {GlyphName: "F", Wx: courierWx},
	"G":              {GlyphName: "G", Wx: courierWx},
	"Gbreve":         {GlyphName: "Gbreve", Wx: courierWx},
	"Gcommaaccent":   {GlyphName: "Gcommaaccent", Wx: courierWx},
	"H":              {GlyphName: "H", Wx: courierWx},
	"I":              {GlyphName: "I", Wx: courierWx},
	"Iacute":         {GlyphName: "Iacute", Wx: courierWx},
	"Icircumflex":    {GlyphName: "Icircumflex", Wx: courierWx},
	"Idieresis":      {GlyphName: "Idieresis", Wx: courierWx},
	"Idotaccent":     {GlyphName: "Idotaccent", Wx: courierWx},
	"Igrave":         {GlyphName: "Igrave", Wx: courierWx},
	"Imacron":        {GlyphName: "Imacron", Wx: courierWx},
	"Iogonek":        {GlyphName: "Iogonek", Wx: courierWx},
	"J":              {GlyphName: "J", Wx: courierWx},
	"K":              {GlyphName: "K", Wx: courierWx},
	"Kcommaaccent":   {GlyphName: "Kcommaaccent", Wx: courierWx},
	"L":              {GlyphName: "L", Wx: courierWx},
	"Lacute":         {GlyphName: "Lacute", Wx: courierWx},
	"Lcaron":         {GlyphName: "Lcaron", Wx: courierWx},
	"Lcommaaccent":   {GlyphName: "Lcommaaccent", Wx: courierWx},
	"Lslash":         {GlyphName: "Lslash", Wx: courierWx},
	"M":              {GlyphName: "M", Wx: courierWx},
	"N":              {GlyphName: "N", Wx: courierWx},
	"Nacute":         {GlyphName: "Nacute", Wx: courierWx},
	"Ncaron":         {GlyphName: "Ncaron", Wx: courierWx},
	"Ncommaaccent":   {GlyphName: "Ncommaaccent", Wx: courierWx},
	"Ntilde":         {GlyphName: "Ntilde", Wx: courierWx},
	"O":              {GlyphName: "O", Wx: courierWx},
	"OE":             {GlyphName: "OE", Wx: courierWx},
	"Oacute":         {GlyphName: "Oacute", Wx: courierWx},
	"Ocircumflex":    {GlyphName: "Ocircumflex", Wx: courierWx},
	"Odieresis":      {GlyphName: "Odieresis", Wx: courierWx},
	"Ograve":         {GlyphName: "Ograve", Wx: courierWx},
	"Ohungarumlaut":  {GlyphName: "Ohungarumlaut", Wx: courierWx},
	"Omacron":        {GlyphName: "Omacron", Wx: courierWx},
	"Oslash":         {GlyphName: "Oslash", Wx: courierWx},
	"Otilde":         {GlyphName: "Otilde", Wx: courierWx},
	"P":              {GlyphName: "P", Wx: courierWx},
	"Q":              {GlyphName: "Q", Wx: courierWx},
	"R":              {GlyphName: "R", Wx: courierWx},
	"Racute":         {GlyphName: "Racute", Wx: courierWx},
	"Rcaron":         {GlyphName: "Rcaron", Wx: courierWx},
	"Rcommaaccent":   {GlyphName: "Rcommaaccent", Wx: courierWx},
	"S":              {GlyphName: "S", Wx: courierWx},
	"Sacute":         {GlyphName: "Sacute", Wx: courierWx},
	"Scaron":         {GlyphName: "Scaron", Wx: courierWx},
	"Scedilla":       {GlyphName: "Scedilla", Wx: courierWx},
	"Scommaaccent":   {GlyphName: "Scommaaccent", Wx: courierWx},
	"T":              {GlyphName: "T", Wx: courierWx},
	"Tcaron":         {GlyphName: "Tcaron", Wx: courierWx},
	"Tcommaaccent":   {GlyphName: "Tcommaaccent", Wx: courierWx},
	"Thorn":          {GlyphName: "Thorn", Wx: courierWx},
	"U":              {GlyphName: "U", Wx: courierWx},
	"Uacute":         {GlyphName: "Uacute", Wx: courierWx},
	"Ucircumflex":    {GlyphName: "Ucircumflex", Wx: courierWx},
	"Udieresis":      {GlyphName: "Udieresis", Wx: courierWx},
	"Ugrave":         {GlyphName: "Ugrave", Wx: courierWx},
	"Uhungarumlaut":  {GlyphName: "Uhungarumlaut", Wx: courierWx},
	"Umacron":        {GlyphName: "Umacron", Wx: courierWx},
	"Uogonek":        {GlyphName: "Uogonek", Wx: courierWx},
	"Uring":          {GlyphName: "Uring", Wx: courierWx},
	"V":              {GlyphName: "V", Wx: courierWx},
	"W":              {GlyphName: "W", Wx: courierWx},
	"X":              {GlyphName: "X", Wx: courierWx},
	"Y":              {GlyphName: "Y", Wx: courierWx},
	"Yacute":         {GlyphName: "Yacute", Wx: courierWx},
	"Ydieresis":      {GlyphName: "Ydieresis", Wx: courierWx},
	"Z":              {GlyphName: "Z", Wx: courierWx},
	"Zacute":         {GlyphName: "Zacute", Wx: courierWx},
	"Zcaron":         {GlyphName: "Zcaron", Wx: courierWx},
	"Zdotaccent":     {GlyphName: "Zdotaccent", Wx: courierWx},
	"a":              {GlyphName: "a", Wx: courierWx},
	"aacute":         {GlyphName: "aacute", Wx: courierWx},
	"abreve":         {GlyphName: "abreve", Wx: courierWx},
	"acircumflex":    {GlyphName: "acircumflex", Wx: courierWx},
	"acute":          {GlyphName: "acute", Wx: courierWx},
	"adieresis":      {GlyphName: "adieresis", Wx: courierWx},
	"ae":             {GlyphName: "ae", Wx: courierWx},
	"agrave":         {GlyphName: "agrave", Wx: courierWx},
	"amacron":        {GlyphName: "amacron", Wx: courierWx},
	"ampersand":      {GlyphName: "ampersand", Wx: courierWx},
	"aogonek":        {GlyphName: "aogonek", Wx: courierWx},
	"aring":          {GlyphName: "aring", Wx: courierWx},
	"asciicircum":    {GlyphName: "asciicircum", Wx: courierWx},
	"asciitilde":     {GlyphName: "asciitilde", Wx: courierWx},
	"asterisk":       {GlyphName: "asterisk", Wx: courierWx},
	"at":             {GlyphName: "at", Wx: courierWx},
	"atilde":         {GlyphName: "atilde", Wx: courierWx},
	"b":              {GlyphName: "b", Wx: courierWx},
	"backslash":      {GlyphName: "backslash", Wx: courierWx},
	"bar":            {GlyphName: "bar", Wx: courierWx},
	"braceleft":      {GlyphName: "braceleft", Wx: courierWx},
	"braceright":     {GlyphName: "braceright", Wx: courierWx},
	"bracketleft":    {GlyphName: "bracketleft", Wx: courierWx},
	"bracketright":   {GlyphName: "bracketright", Wx: courierWx},
	"breve":          {GlyphName: "breve", Wx: courierWx},
	"brokenbar":      {GlyphName: "brokenbar", Wx: courierWx},
	"bullet":         {GlyphName: "bullet", Wx: courierWx},
	"c":              {GlyphName: "c", Wx: courierWx},
	"cacute":         {GlyphName: "cacute", Wx: courierWx},
	"caron":          {GlyphName: "caron", Wx: courierWx},
	"ccaron":         {GlyphName: "ccaron", Wx: courierWx},
	"ccedilla":       {GlyphName: "ccedilla", Wx: courierWx},
	"cedilla":        {GlyphName: "cedilla", Wx: courierWx},
	"cent":           {GlyphName: "cent", Wx: courierWx},
	"circumflex":     {GlyphName: "circumflex", Wx: courierWx},
	"colon":          {GlyphName: "colon", Wx: courierWx},
	"comma":          {GlyphName: "comma", Wx: courierWx},
	"commaaccent":    {GlyphName: "commaaccent", Wx: courierWx},
	"copyright":      {GlyphName: "copyright", Wx: courierWx},
	"currency":       {GlyphName: "currency", Wx: courierWx},
	"d":              {GlyphName: "d", Wx: courierWx},
	"dagger":         {GlyphName: "dagger", Wx: courierWx},
	"daggerdbl":      {GlyphName: "daggerdbl", Wx: courierWx},
	"dcaron":         {GlyphName: "dcaron", Wx: courierWx},
	"dcroat":         {GlyphName: "dcroat", Wx: courierWx},
	"degree":         {GlyphName: "degree", Wx: courierWx},
	"dieresis":       {GlyphName: "dieresis", Wx: courierWx},
	"divide":         {GlyphName: "divide", Wx: courierWx},
	"dollar":         {GlyphName: "dollar", Wx: courierWx},
	"dotaccent":      {GlyphName: "dotaccent", Wx: courierWx},
	"dotlessi":       {GlyphName: "dotlessi", Wx: courierWx},
	"e":              {GlyphName: "e", Wx: courierWx},
	"eacute":         {GlyphName: "eacute", Wx: courierWx},
	"ecaron":         {GlyphName: "ecaron", Wx: courierWx},
	"ecircumflex":    {GlyphName: "ecircumflex", Wx: courierWx},
	"edieresis":      {GlyphName: "edieresis", Wx: courierWx},
	"edotaccent":     {GlyphName: "edotaccent", Wx: courierWx},
	"egrave":         {GlyphName: "egrave", Wx: courierWx},
	"eight":          {GlyphName: "eight", Wx: courierWx},
	"ellipsis":       {GlyphName: "ellipsis", Wx: courierWx},
	"emacron":        {GlyphName: "emacron", Wx: courierWx},
	"emdash":         {GlyphName: "emdash", Wx: courierWx},
	"endash":         {GlyphName: "endash", Wx: courierWx},
	"eogonek":        {GlyphName: "eogonek", Wx: courierWx},
	"equal":          {GlyphName: "equal", Wx: courierWx},
	"eth":            {GlyphName: "eth", Wx: courierWx},
	"exclam":         {GlyphName: "exclam", Wx: courierWx},
	"exclamdown":     {GlyphName: "exclamdown", Wx: courierWx},
	"f":              {GlyphName: "f", Wx: courierWx},
	"fi":             {GlyphName: "fi", Wx: courierWx},
	"five":           {GlyphName: "five", Wx: courierWx},
	"fl":             {GlyphName: "fl", Wx: courierWx},
	"florin":         {GlyphName: "florin", Wx: courierWx},
	"four":           {GlyphName: "four", Wx: courierWx},
	"fraction":       {GlyphName: "fraction", Wx: courierWx},
	"g":              {GlyphName: "g", Wx: courierWx},
	"gbreve":         {GlyphName: "gbreve", Wx: courierWx},
	"gcommaaccent":   {GlyphName: "gcommaaccent", Wx: courierWx},
	"germandbls":     {GlyphName: "germandbls", Wx: courierWx},
	"grave":          {GlyphName: "grave", Wx: courierWx},
	"greater":        {GlyphName: "greater", Wx: courierWx},
	"greaterequal":   {GlyphName: "greaterequal", Wx: courierWx},
	"guillemotleft":  {GlyphName: "guillemotleft", Wx: courierWx},
	"guillemotright": {GlyphName: "guillemotright", Wx: courierWx},
	"guilsinglleft":  {GlyphName: "guilsinglleft", Wx: courierWx},
	"guilsinglright": {GlyphName: "guilsinglright", Wx: courierWx},
	"h":              {GlyphName: "h", Wx: courierWx},
	"hungarumlaut":   {GlyphName: "hungarumlaut", Wx: courierWx},
	"hyphen":         {GlyphName: "hyphen", Wx: courierWx},
	"i":              {GlyphName: "i", Wx: courierWx},
	"iacute":         {GlyphName: "iacute", Wx: courierWx},
	"icircumflex":    {GlyphName: "icircumflex", Wx: courierWx},
	"idieresis":      {GlyphName: "idieresis", Wx: courierWx},
	"igrave":         {GlyphName: "igrave", Wx: courierWx},
	"imacron":        {GlyphName: "imacron", Wx: courierWx},
	"iogonek":        {GlyphName: "iogonek", Wx: courierWx},
	"j":              {GlyphName: "j", Wx: courierWx},
	"k":              {GlyphName: "k", Wx: courierWx},
	"kcommaaccent":   {GlyphName: "kcommaaccent", Wx: courierWx},
	"l":              {GlyphName: "l", Wx: courierWx},
	"lacute":         {GlyphName: "lacute", Wx: courierWx},
	"lcaron":         {GlyphName: "lcaron", Wx: courierWx},
	"lcommaaccent":   {GlyphName: "lcommaaccent", Wx: courierWx},
	"less":           {GlyphName: "less", Wx: courierWx},
	"lessequal":      {GlyphName: "lessequal", Wx: courierWx},
	"logicalnot":     {GlyphName: "logicalnot", Wx: courierWx},
	"lozenge":        {GlyphName: "lozenge", Wx: courierWx},
	"lslash":         {GlyphName: "lslash", Wx: courierWx},
	"m":              {GlyphName: "m", Wx: courierWx},
	"macron":         {GlyphName: "macron", Wx: courierWx},
	"minus":          {GlyphName: "minus", Wx: courierWx},
	"mu":             {GlyphName: "mu", Wx: courierWx},
	"multiply":       {GlyphName: "multiply", Wx: courierWx},
	"n":              {GlyphName: "n", Wx: courierWx},
	"nacute":         {GlyphName: "nacute", Wx: courierWx},
	"ncaron":         {GlyphName: "ncaron", Wx: courierWx},
	"ncommaaccent":   {GlyphName: "ncommaaccent", Wx: courierWx},
	"nine":           {GlyphName: "nine", Wx: courierWx},
	"notequal":       {GlyphName: "notequal", Wx: courierWx},
	"ntilde":         {GlyphName: "ntilde", Wx: courierWx},
	"numbersign":     {GlyphName: "numbersign", Wx: courierWx},
	"o":              {GlyphName: "o", Wx: courierWx},
	"oacute":         {GlyphName: "oacute", Wx: courierWx},
	"ocircumflex":    {GlyphName: "ocircumflex", Wx: courierWx},
	"odieresis":      {GlyphName: "odieresis", Wx: courierWx},
	"oe":             {GlyphName: "oe", Wx: courierWx},
	"ogonek":         {GlyphName: "ogonek", Wx: courierWx},
	"ograve":         {GlyphName: "ograve", Wx: courierWx},
	"ohungarumlaut":  {GlyphName: "ohungarumlaut", Wx: courierWx},
	"omacron":        {GlyphName: "omacron", Wx: courierWx},
	"one":            {GlyphName: "one", Wx: courierWx},
	"onehalf":        {GlyphName: "onehalf", Wx: courierWx},
	"onequarter":     {GlyphName: "onequarter", Wx: courierWx},
	"onesuperior":    {GlyphName: "onesuperior", Wx: courierWx},
	"ordfeminine":    {GlyphName: "ordfeminine", Wx: courierWx},
	"ordmasculine":   {GlyphName: "ordmasculine", Wx: courierWx},
	"oslash":         {GlyphName: "oslash", Wx: courierWx},
	"otilde":         {GlyphName: "otilde", Wx: courierWx},
	"p":              {GlyphName: "p", Wx: courierWx},
	"paragraph":      {GlyphName: "paragraph", Wx: courierWx},
	"parenleft":      {GlyphName: "parenleft", Wx: courierWx},
	"parenright":     {GlyphName: "parenright", Wx: courierWx},
	"partialdiff":    {GlyphName: "partialdiff", Wx: courierWx},
	"percent":        {GlyphName: "percent", Wx: courierWx},
	"period":         {GlyphName: "period", Wx: courierWx},
	"periodcentered": {GlyphName: "periodcentered", Wx: courierWx},
	"perthousand":    {GlyphName: "perthousand", Wx: courierWx},
	"plus":           {GlyphName: "plus", Wx: courierWx},
	"plusminus":      {GlyphName: "plusminus", Wx: courierWx},
	"q":              {GlyphName: "q", Wx: courierWx},
	"question":       {GlyphName: "question", Wx: courierWx},
	"questiondown":   {GlyphName: "questiondown", Wx: courierWx},
	"quotedbl":       {GlyphName: "quotedbl", Wx: courierWx},
	"quotedblbase":   {GlyphName: "quotedblbase", Wx: courierWx},
	"quotedblleft":   {GlyphName: "quotedblleft", Wx: courierWx},
	"quotedblright":  {GlyphName: "quotedblright", Wx: courierWx},
	"quoteleft":      {GlyphName: "quoteleft", Wx: courierWx},
	"quoteright":     {GlyphName: "quoteright", Wx: courierWx},
	"quotesinglbase": {GlyphName: "quotesinglbase", Wx: courierWx},
	"quotesingle":    {GlyphName: "quotesingle", Wx: courierWx},
	"r":              {GlyphName: "r", Wx: courierWx},
	"racute":         {GlyphName: "racute", Wx: courierWx},
	"radical":        {GlyphName: "radical", Wx: courierWx},
	"rcaron":         {GlyphName: "rcaron", Wx: courierWx},
	"rcommaaccent":   {GlyphName: "rcommaaccent", Wx: courierWx},
	"registered":     {GlyphName: "registered", Wx: courierWx},
	"ring":           {GlyphName: "ring", Wx: courierWx},
	"s":              {GlyphName: "s", Wx: courierWx},
	"sacute":         {GlyphName: "sacute", Wx: courierWx},
	"scaron":         {GlyphName: "scaron", Wx: courierWx},
	"scedilla":       {GlyphName: "scedilla", Wx: courierWx},
	"scommaaccent":   {GlyphName: "scommaaccent", Wx: courierWx},
	"section":        {GlyphName: "section", Wx: courierWx},
	"semicolon":      {GlyphName: "semicolon", Wx: courierWx},
	"seven":          {GlyphName: "seven", Wx: courierWx},
	"six":            {GlyphName: "six", Wx: courierWx},
	"slash":          {GlyphName: "slash", Wx: courierWx},
	"space":          {GlyphName: "space", Wx: courierWx},
	"sterling":       {GlyphName: "sterling", Wx: courierWx},
	"summation":      {GlyphName: "summation", Wx: courierWx},
	"t":              {GlyphName: "t", Wx: courierWx},
	"tcaron":         {GlyphName: "tcaron", Wx: courierWx},
	"tcommaaccent":   {GlyphName: "tcommaaccent", Wx: courierWx},
	"thorn":          {GlyphName: "thorn", Wx: courierWx},
	"three":          {GlyphName: "three", Wx: courierWx},
	"threequarters":  {GlyphName: "threequarters", Wx: courierWx},
	"threesuperior":  {GlyphName: "threesuperior", Wx: courierWx},
	"tilde":          {GlyphName: "tilde", Wx: courierWx},
	"trademark":      {GlyphName: "trademark", Wx: courierWx},
	"two":            {GlyphName: "two", Wx: courierWx},
	"twosuperior":    {GlyphName: "twosuperior", Wx: courierWx},
	"u":              {GlyphName: "u", Wx: courierWx},
	"uacute":         {GlyphName: "uacute", Wx: courierWx},
	"ucircumflex":    {GlyphName: "ucircumflex", Wx: courierWx},
	"udieresis":      {GlyphName: "udieresis", Wx: courierWx},
	"ugrave":         {GlyphName: "ugrave", Wx: courierWx},
	"uhungarumlaut":  {GlyphName: "uhungarumlaut", Wx: courierWx},
	"umacron":        {GlyphName: "umacron", Wx: courierWx},
	"underscore":     {GlyphName: "underscore", Wx: courierWx},
	"uogonek":        {GlyphName: "uogonek", Wx: courierWx},
	"uring":          {GlyphName: "uring", Wx: courierWx},
	"v":              {GlyphName: "v", Wx: courierWx},
	"w":              {GlyphName: "w", Wx: courierWx},
	"x":              {GlyphName: "x", Wx: courierWx},
	"y":              {GlyphName: "y", Wx: courierWx},
	"yacute":         {GlyphName: "yacute", Wx: courierWx},
	"ydieresis":      {GlyphName: "ydieresis", Wx: courierWx},
	"yen":            {GlyphName: "yen", Wx: courierWx},
	"z":              {GlyphName: "z", Wx: courierWx},
	"zacute":         {GlyphName: "zacute", Wx: courierWx},
	"zcaron":         {GlyphName: "zcaron", Wx: courierWx},
	"zdotaccent":     {GlyphName: "zdotaccent", Wx: courierWx},
	"zero":           {GlyphName: "zero", Wx: courierWx},
}

// Courier-Bold font metrics loaded from afms/Courier-Bold.afm.  See afms/MustRead.html for license information.
//
// TODO(dennwc): unexport
var CourierBoldCharMetrics = CourierCharMetrics

// CourierBoldObliqueCharMetrics are the font metrics loaded from afms/Courier-BoldOblique.afm.
// See afms/MustRead.html for license information.
//
// TODO(dennwc): unexport
var CourierBoldObliqueCharMetrics = CourierCharMetrics

// CourierObliqueCharMetrics are the font metrics loaded from afms/Courier-Oblique.afm.
// See afms/MustRead.html for license information.
//
// TODO(dennwc): unexport
var CourierObliqueCharMetrics = CourierCharMetrics
