//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package jbig2 ;import (_g "github.com/unidoc/unipdf/v3/internal/bitwise";_cc "github.com/unidoc/unipdf/v3/internal/jbig2/decoder";_ca "github.com/unidoc/unipdf/v3/internal/jbig2/document";_gf "github.com/unidoc/unipdf/v3/internal/jbig2/document/segments";
_d "github.com/unidoc/unipdf/v3/internal/jbig2/errors";_c "sort";);func DecodeBytes (encoded []byte ,parameters _cc .Parameters ,globals ...Globals )([]byte ,error ){var _dd Globals ;if len (globals )> 0{_dd =globals [0];};_b ,_cab :=_cc .Decode (encoded ,parameters ,_dd .ToDocumentGlobals ());
if _cab !=nil {return nil ,_cab ;};return _b .DecodeNextPage ();};type Globals map[int ]*_gf .Header ;func (_fdg Globals )ToDocumentGlobals ()*_ca .Globals {if _fdg ==nil {return nil ;};_ee :=[]*_gf .Header {};for _ ,_eg :=range _fdg {_ee =append (_ee ,_eg );
};_c .Slice (_ee ,func (_bd ,_cf int )bool {return _ee [_bd ].SegmentNumber < _ee [_cf ].SegmentNumber });return &_ca .Globals {Segments :_ee };};func DecodeGlobals (encoded []byte )(Globals ,error ){const _cb ="\u0044\u0065\u0063\u006f\u0064\u0065\u0047\u006c\u006f\u0062\u0061\u006c\u0073";
_e :=_g .NewReader (encoded );_a ,_cd :=_ca .DecodeDocument (_e ,nil );if _cd !=nil {return nil ,_d .Wrap (_cd ,_cb ,"");};if _a .GlobalSegments ==nil ||(_a .GlobalSegments .Segments ==nil ){return nil ,_d .Error (_cb ,"\u006eo\u0020\u0067\u006c\u006f\u0062\u0061\u006c\u0020\u0073\u0065\u0067m\u0065\u006e\u0074\u0073\u0020\u0066\u006f\u0075\u006e\u0064");
};_bc :=Globals {};for _ ,_ge :=range _a .GlobalSegments .Segments {_bc [int (_ge .SegmentNumber )]=_ge ;};return _bc ,nil ;};